import Foundation
import HPatch
import Testing

// Fixtures were generated by hdiffz v5.1.3 from old.bin -> new.bin.
struct HPatchTests {
    let fixtures = Bundle.module.resourceURL!.appendingPathComponent("Fixtures")
    let output = FileManager.default.temporaryDirectory
        .appendingPathComponent("hpatch-\(UUID().uuidString).bin")

    func fixture(_ name: String) -> URL { fixtures.appendingPathComponent(name) }

    @Test(arguments: [
        "zlib.diff", "lzma.diff", "lzma2.diff", "zstd.diff", "bzip2.diff",
        "sd-zstd.diff", "wd-zstd.diff", "vcdiff.diff", "vcdiff-xz.diff", "bsdiff.diff",
    ])
    func appliesDiff(_ diff: String) throws {
        defer { try? FileManager.default.removeItem(at: output) }
        try HPatch.apply(old: fixture("old.bin"), diff: fixture(diff), output: output)
        #expect(try Data(contentsOf: output) == Data(contentsOf: fixture("new.bin")))
    }

    @Test(arguments: ["sd-zstd.diff", "wd-zstd.diff"])
    func appliesDiffMultithreaded(_ diff: String) throws {
        defer { try? FileManager.default.removeItem(at: output) }
        try HPatch.apply(
            old: fixture("old.bin"), diff: fixture(diff), output: output,
            options: .init(threadCount: 4)
        )
        #expect(try Data(contentsOf: output) == Data(contentsOf: fixture("new.bin")))
    }

    @Test func appliesDiffFromEmptyOld() throws {
        defer { try? FileManager.default.removeItem(at: output) }
        try HPatch.apply(old: nil, diff: fixture("from-empty.diff"), output: output)
        #expect(try Data(contentsOf: output) == Data(contentsOf: fixture("new.bin")))
    }

    @Test func appliesDiffAsync() async throws {
        defer { try? FileManager.default.removeItem(at: output) }
        try await HPatch.apply(old: fixture("old.bin"), diff: fixture("zstd.diff"), output: output)
        #expect(try Data(contentsOf: output) == Data(contentsOf: fixture("new.bin")))
    }

    @Test func missingDiffThrowsOpenRead() {
        #expect(throws: HPatchError.openRead) {
            try HPatch.apply(old: fixture("old.bin"), diff: fixture("nope.diff"), output: output)
        }
    }

    @Test func garbageDiffThrows() {
        defer { try? FileManager.default.removeItem(at: output) }
        #expect(throws: HPatchError.self) {
            try HPatch.apply(old: fixture("old.bin"), diff: fixture("new.bin"), output: output)
        }
    }

    @Test func wrongOldFileThrows() {
        defer { try? FileManager.default.removeItem(at: output) }
        #expect(throws: HPatchError.self) {
            try HPatch.apply(old: fixture("new.bin"), diff: fixture("wd-zstd.diff"), output: output)
        }
    }

    @Test func invalidThreadCountThrowsOptions() {
        #expect(throws: HPatchError.options) {
            try HPatch.apply(
                old: fixture("old.bin"), diff: fixture("zstd.diff"), output: output,
                options: .init(threadCount: 0)
            )
        }
    }
}
